#------------------------------------------------------
# Generate results 
#------------------------------------------------------
import pylab as pltss
from pylab import *
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.io
import os.path

# Make sure that caffe is on the python path:
caffe_root = '/Users/ashish/caffe/'  # this file is expected to be in {caffe_root}/examples
import sys
sys.path.insert(0, caffe_root + 'python')

import caffe

from datetime import datetime
import glob
import os

# Set the right path to your model definition file, pretrained model weights,
# and the image you would like to classify.
MODEL_FILE = 'deploy_sun_ws.prototxt'
PRETRAINED = 'caffe_sun_ws.caffemodel'

import os

caffe.set_mode_cpu()
net = caffe.Classifier(MODEL_FILE, PRETRAINED,
                       mean=np.load('sunours_mean.npy').mean(1).mean(1),
                       channel_swap=(2,1,0),
                       raw_scale=255,
                       image_dims=(256, 256))


imPaths = ['/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_alanoefxfkxkbzcm.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_avordrjyvvdmvakj.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_anxdbjccvpwtjjzo.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_acnqjgrdpxwdvyqs.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_ahxadsvoikphqvwo.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_aaeoladfaeeaszvm.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_actpreoecwqcuvcj.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/revolving_door/sun_adbfovrvbanhmzfy.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aqyolggzcyndlplt.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_adpqrxpljrrbygfl.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_ajdpxftllsqlbbgi.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_arhmodxttgcibjki.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_abbvceinfedonlzi.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_alrlxmezquimqcbe.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aeepukbhljxkjreg.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aihoxlldnqpevwuf.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_annbzsybfgchyqve.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_akosyssdqjdiwvhh.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aodxzimgahxchttz.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_acdktbkffvsgovcx.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aogmpsdumddqfczc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_atemowkutzcahdcc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_anwdfsmyictldtnb.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_abdhccnibdvhkudc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_agtdrungmteiwugb.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aiarammdbhcpayaa.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_afxlwtprkbhkomcr.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_aaihjkzhwqutuoli.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/rectory/sun_ajugmttwpoysoddk.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_anrrldeaibfcbixl.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_axctsxxhqpuiiuba.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_axakvdmxqivzviom.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_aihbsgyywkujftoc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_aiffdbziadfycdya.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_adstmlzqjhlsbdtp.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_aflldvpqqfxbvdvf.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_afjesifzfuxbfihw.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_arxxiaqkixigdstc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_agfclmkfwcbxsigw.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_anrsdjfhnebvutjc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_ahhouyiqbadneuqn.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_atsakgtjuhwgenuw.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_aspappciiqdnzgyr.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_ahlrosembmwfrvzv.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_ahsecjlbmqdzonds.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_awlpuyiilzbtvegj.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_avazekslxtepgcuf.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_ahsyobaxiibstttx.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railway_yard/sun_aouopgvwisxlkrjf.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_avvhxfqdeamwgfyn.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_acnzwyxhpyptpbnv.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_arfdlzsnmglcvikh.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_amrwwigmaxipolze.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aaxdpgpohhvyemvc.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_arpwdgrcqacfdkgo.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_akbtbukzosajhuar.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aprqkpblphmpgoow.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_apygwbawndrfxvof.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aftveaxnfsmrlecd.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aivdylrawbmhryfp.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_agpyysqisrrdxcug.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_abeyrlvatsozwrpr.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_algpbuhfpwsomlds.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_abuxdbyqfhrcggnx.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_anwjwfhvpwkeuezw.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aiggqezznzfpvuqz.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_aimowamuhxdznylm.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_apkyagytekpxaoeq.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_atavhlqptjhltvmg.jpg',
'/Users/ashish/vision-project/data/SUN/images/r/railroad_track/sun_attdtbujlaxisvly.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dnlccktninwdbfau.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dzhwswbvbqjxcroc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dsmyvudebmnfehsw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dzpeknfkkjavbrhl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dawtdtczjouayzyd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_difhensjljmbisjf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_drxixpfpaqrexxlr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dcsdxcgfavdacofw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dmrlifkpqbljpuxv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dlzfwhceveeezdxn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dlwwqbuhdxwhjpqv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dzkvwjxvacljrovj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dhhtoewstrmewzpk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_drhoxsjriqfimjsy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dziootoaqadrlowa.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dfpawuyjlarwzjtc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_drdyikpagynsjvbn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dqsjjjemrfycaery.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dgppihvxqkehkatq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dwwsdcrjvzobrxfl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/skatepark/sun_dnrhfvhovooimfds.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aejteaemukimqsxl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_abymvkysofygjwtd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aiqvqqtdwwqjlklf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_atbytjwdlthaucqy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aqamvzlfygthegrn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_anpggmdqwhczgviu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_agrpnplwskvcwhif.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_alhdepdtjqdtnunt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_agbdghclxjabmafw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_bmqqyjzkqtdvpeor.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_agqktwxavhwvncwa.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_afnrewnqcwptvpfo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_adewkhtpwxfcsjtx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_afbkdhekqhtwxort.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_bafcibphfghwjfge.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aguhngholwzfuggd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aittiyoglaboqxis.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aqntixynmwqeovdj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_aqgkwjnyufarwztm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_alqxaqriwoytjgab.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sewing_room/sun_amxueyjuvabjrgbz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_auvrhbrwgcqafzzq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aeugngpyukkejjpi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bimidwcnomqbuksl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bmuqherodwkawsnj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aanhvdjuegetwpri.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bajlpspbjeucxzla.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aclpxkuceoiqntfa.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bhjpzxukfmvowhzs.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_blhhmakleyrtbpxr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aopyrioirmplcrjx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_awbbqouxfsjchjyh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_amhnykwhaivzjnzm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bkdmqjeghlvianhq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aoabjwmkftwynqvq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bjfbkseahibknawg.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bimdpagwyqrufmzk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aaguxgrqaehrwaip.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_bfqfwsirqinlzclr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_axagkcctjrssmrst.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shower/sun_aaueptrvafpquklh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_acjuvobqlxmsvicj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_amqmrjuticynnigx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aftiprtlmksbzngk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_arhkghsagofjrsfm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_absstflrntihapyw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_atxedlizbmehuwkg.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_ahatexnizqmlhidu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aefumabnxdqgthzl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_anljvsvlxmgijzit.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aadbgvqukuoscmnz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_ahwuftkxybfmtywl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_avqdwprzuldnyjlx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_annvhgogezmnpbpz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_amfszgsfnkdaikkg.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_agqsrxqlloasnyee.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_akfmjuytwlssjqrl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aaekcfaaxzzkxcwj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_alqhlzxmkarlbzkz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aoovvcywkikwrmda.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shipping_room/sun_aqwsvoxjvjanstge.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bnctbyjqifwbewiv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bkjhypyrkpyippdx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bojfjvkigrklmdas.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_btlidkoxhjhbkzsi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bcnqrszitqwqanrp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bausmnodnjqbpbut.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_behnhvbjsjelnylk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_apvpguptxubhzjxv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bxdecaizhvwyoxia.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bavddhlwgzvwvouo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bckdxjkxkmpsbvst.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_blfvbhauzlupywod.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bvltuubfbmepqeyz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_axzrkszfeebcopwe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bjqwdukgflqtqxxu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bcpvlvdwwqptqnhq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bjfvregelvrttell.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bgclmwaheocfjzyb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bgzfngqitbdcxzuw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_besrfhnbvstifnnt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/ski_jump/sun_bhspgqimhhtrjibl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aalarxcfbjmorjip.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_afprixwlaktdsguz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_anxzechmggrinczx-1.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_alymaapahjccwqhe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_agdbqxlmmdjvovpx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aqnvceezbmmlxsyu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_anxzechmggrinczx-0.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aaezskjybhffntmq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aderjvelhffajiaf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_adohehynbddkeohk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_ahikoufbbdflnzqu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_arhprazapdhihndq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_adwbytzfedlwvweh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aajswqivsnxdbejn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_abzkhzmxdjrfjpjz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aoeudylnmryvayrz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_anxzechmggrinczx-2.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_aomkoqvsvxknyaqw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_adakllrplmpnkpwu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_ajipbobzpolvnanl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_amvxrmygfpfhradx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/stone_circle/sun_alauoqdceupxwjwt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_ajguxbdzusoldgve.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_anvamvaanswnwpuw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_ateiridxswpywmyb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_aebotrzyrcwnlvgr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_bdlzgetcvtiesoki.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_arscubfhzahugepe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_aoptqugxjfwllelq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_avlkvghnwtbeboxw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_aqbsslordankdsxp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_aarefyqnkoczxejm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_adffenrqtyjaednt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_ajtyojxykwacqrsv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_abvbcrewqpsorqay.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_ayhipiwwtrxdapjy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_ajyepvfgqlswktqb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_aoazhaxmbwiqphke.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_agoxmmsddmqpppjf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_anlugbjswgtxfljc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_anjbxcgxozfqucly.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_axfmkvakpsuejrwb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbox/sun_atuyjjeksbtqkrnb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_awqfxqgumqzgvovp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_aiduueqzjitbivyh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_azsodalnmbonqiga.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_bmrbcfrctouuaeyn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_bbwjeilorbjvkuwe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_atymoyqvcpmosbfx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_azprvhrhjymtsiza.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_aqmitgiqzuzhtazv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_badlitmwagrvldth.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_beilfssfkixizrit.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_ajadqbuethnwmouf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_ahcpgbtvsgkbahgn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_blijglkezcooyomm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_bfinedihjbomjnyf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_bcywjqchsxqmzook.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_aezxzpehhhxtaawh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_bfsnepzyrtjigzqo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_ahyjjeawjdslzite.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_asogcyrurecgnedz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_aoxvmoamyjmvdfwd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sawmill/sun_atxcxgtlxbctphze.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abcravnfiujxjjqo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abrsvgqwevwxdnbp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aaigjczwiotsluie.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abxvyqepasckpkgh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abfelgkioejrcugp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aaeluqrkikjbtquv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aadhshmrjrbucdky.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aabghtsyctpcjvlc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aajacutyiukwhdfi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aapkxljwudmsvqec.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aaokytxyrympbpkv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abtbnjspetmoknad.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aayameemlzdjkinb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abhjteqstcfyacpq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abwfccwqxsmkoqme.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_afhvalwknjrfpdjm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aaeryjozzmanouqj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aakfhsatwzotyzmi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abqzvytgmhripkgv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_abxoxzsddjzrgdfi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/street/sun_aaoukmfcmvbaszsu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_azvghwbqurniwlec.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ciifteeudwpxupnw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ajscetskiwaukgin.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_amfsfhvduayinuhx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_afpbvjgphoknshwq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_bllgbovxfdgxzqmz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ahtpokzlaophrxef.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_agjlpjejeyncksoy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_amnmxbybloeimbcx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_atbapfxfhmlzcdrn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_asutjxowljdnlybt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_bprwpdclbqbyzynw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_aqvgzriiamtoqfjz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_blaqevbwpjaqqdqz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ajqbxjvwcvhpbvtu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_afouusminlagzmzp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_apxdlklioepthkgw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ajhtontofvkavmvy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_ayjbewhhjzxrnqof.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_beqrfxahgpuoswoh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sandbar/sun_adovqdocqlbuyiix.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_alxsfatxpgajixvc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_atajjswvckkcqcwo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aswtdqjjllvsurdo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aasyaeqgzlvuhmhm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aektkszbzylzxsau.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_akfnsopvdneolmpr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_attlaclfqetjkdsv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_ahupxvtozajhsxiv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_abdonoqotoamyyqr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aeatifohhumxwnhp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_amxvvffqbbdtytyo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_amyailzqcgsdjjwr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aslikgdkitfyvjpz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_ajftrjbkoiigpzuh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_annvgtlmuwwedmqd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_ahjdbigfnmtsmalr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_alozdqcwmlshqlrd.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_ainurvhnzwlpysgg.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_atyrmvomrylmfcit.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aqgmukrxojttvyoh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/shopfront/sun_aohpgleqauhznnpw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_bbnqqcqltywnhcyb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_admihcbowgthfhkh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_agtqwtdcgzjtwqrr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_ajlxqauxgfmrxgjv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_bgxiscbsnyvimyxs.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_alwmzpuogkfjpmmz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_asatxpkpcyudrxxu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_axcbogyofpshqlst.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_apjoydaxjpnrvlzj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_atnvwitjjzxunhrz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_bfqoniukbjtgrmqe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_arhhlwvnudfkvxad.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_ahlaumnhkwidwgbe.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_arebqfwfopivbfzi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_akxpaebnsevtoyrz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_aifjqzovrzesgkfp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_afpbhjqtgoanfngt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_anzawmxkxsjgvfqo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_bfzqbbnzozzitetz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/seawall/sun_agghofkiczyylgos.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_bbislufwxbqxaiyp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_aojguqaikznzxots.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_bavyiduayxocghbt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_aidlpfegwmrtknwt.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_azbtmgtnnvynyafc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_avghwzqivrkeyvzu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_ahxezklmrslnrswb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_agzdrnnbkfjylobs.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_abeyqxbosxdftlhf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_akadtrfkzsamtvxi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_aoerrkadsbulkntq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_aqpoipuofxrlgutf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_akaxyluefrruidfk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_agygishhtslmhoyj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_adbjuxgmvrwhhoax.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_agoepipinsdjpdfl.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_awgmsljxluyoueit.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_anrdixmszuoqslwr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_ahshuowrzgcbuetz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/sacristy/sun_acmkybbwnpoujhqf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_baguoxlthfferyai.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_beieuxoppobvqyaf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bgqbmwodnlxqnklk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_atihwhawrewecoem.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_beojgtkkdmvqunoh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_atuepvqvvkaksotb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bibygqkpcxqycigz.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_aogstxnekzdfsaae.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_aquxqpvoxvmwkuom.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_atjhdqgllveruivn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_ajnypogktiurcmvb.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bghkaixxgsrdbcoj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bjoeahjyofgmdehw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_aezajrlkwypzxdlx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bgjarkqyxhtlpcte.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_acpyufzdkejgiszk.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bdwgcidhmzygpfpg.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_baorpzqjcpfvnxvx.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_babwvttncoffagty.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_awpljhtawococmwc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/strip_mall/sun_bqskgwesmmqnhppa.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_apyhdzepkieawmen.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_afkbokgiheoaqqnu.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_adakrksiaupvjycv.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aajjojbiiausznir.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aoelelvauwbnlcbf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_atkeojyllqgkspvo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aizvrgibpcogrktc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aosdnsncidjlsigo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_agwqeyrebsushgor.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_arnwoudxknckngch.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_axquqdamuigxcrli.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aixfcquvrskedccq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_agpcwfkfddyvygcn.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aqzyitmfaaaywmpi.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_akcjuirleravrmod.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_alxlkpleaypfwgjp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_axctahdolapwfxij.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aqamgcrfihrmucsy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_axjcjlsfmohuknen.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_aljhbekhbjprhwrr.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/swamp/sun_ayjgoxehlvcavbnm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_awpzupsclixjrohw.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_auutbcqfhcoepljq.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_ayfvtsfhmnxcypih.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_aoaxizkleuypncnm.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_alhavfbsfrntubql.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_anjzfezjezfmufte.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_azeentyoezjzddbj.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_adhpokoikfwedglh.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_assrbwmewzkeqpfc.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_azpdfbdhaczidquo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_aqnustnejitcfcgp.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_aqlfunknsnmrjjdy.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_benwwwwdcpyekwgo.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_akmogtvirbfpomqs.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_aaayyldbvgqtwpvf.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_ahbwgboecahypeca.jpg',
'/Users/ashish/vision-project/data/SUN/images/s/slum/sun_aunmqsvyxrndgmlk.jpg']


feat_vecs = np.zeros((1, 4096))
batch_size = 50
num_im = len(imPaths)

print(num_im)
print(batch_size)

iter_ = 0
max_iter = len(imPaths) / batch_size
startTime = datetime.now()
while imPaths:
    iter_ += 1
    print('iteration', iter_, 'out of', max_iter)
    ims = []
    images = []
    
    for i in range(batch_size):
        if imPaths:
            temp = imPaths.pop()
            # print('image no.', (iter_-1)*batch_size + i + 1, 'out of', num_im)
            print(temp)
            ims.append(temp)
        else:
            break

    for im in ims:
        image = caffe.io.load_image(im)
        images.append(image)
        
    # predict takes any number of images, and formats them for the Caffe net automatically
    prediction = net.predict(images, oversample = False)
    feat = net.blobs['fc7'].data
    feat_vecs = np.vstack([feat_vecs, feat])
    print datetime.now() - startTime


feat_vecs = feat_vecs[1:num_im+1, :]
print(feat_vecs.shape)
np.save('feat_vecs_debug.npy', feat_vecs)